-- ============================================================
-- ArtistOS Phase 27: grant finder refresh (44 verified programs)
-- Verified against official sites, Sept 24, 2026.
-- deadline NULL = rolling, or next date not announced yet (see eligibility_notes).
-- Safe to re-run.
-- ============================================================
ALTER TABLE public.opportunities ADD COLUMN IF NOT EXISTS last_verified DATE;
ALTER TABLE public.opportunities ADD COLUMN IF NOT EXISTS source_url TEXT;

-- Retire every older listing (placeholder deadlines). Rows are kept so saved matches/applications still resolve.
UPDATE public.opportunities SET is_active = false, updated_at = now()
WHERE last_verified IS NULL AND is_active = true;

INSERT INTO public.opportunities
 (title, organization, opportunity_type, description, amount_min, amount_max, deadline, url, eligibility_notes, mediums, location_scope, location_detail, career_stage, application_fee, is_active, last_verified, source_url)
SELECT * FROM (VALUES
('Southern Prize and State Fellowships for Visual Arts','South Arts','fellowship','Nine $5,000 state fellowships, one per South Arts state; two fellows are then chosen for the Southern Prize ($25,000 winner, $10,000 finalist) plus a Hambidge Center residency.',5000,25000,NULL,'https://www.southarts.org/grants-opportunities/southern-prize-and-state-fellowships-visual-arts','Individual visual artists 18+ who have lived in AL, FL, GA, KY, LA, MS, NC, SC or TN for at least 2 years. Students can''t apply. $25 fee (waivers available). Next deadline not yet announced; it is usually in February or March. Check the site in early 2027.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'regional','South Arts region: AL, FL, GA, KY, LA, MS, NC, SC, TN','any',25,true,DATE '2026-09-24','https://www.southarts.org/grants-opportunities/southern-prize-and-state-fellowships-visual-arts'),
('Emerging Traditional Artists Program','South Arts','grant','$5,000 unrestricted award plus free virtual professional development and peer mentoring for early-career folk and traditional artists.',5000,5000,'2026-09-30'::date,'https://www.southarts.org/grants-opportunities/emerging-traditional-artists-program','Early-career folk and traditional artists (weaving, basketry, pottery, quilting and similar), 18+. You must have lived at least 2 years in an Appalachian Regional Commission county or a Delta Regional Authority county/parish in AL, GA, KY, LA, MS, NC, SC or TN. Due 5pm ET. No fee.',ARRAY['textile','ceramics','sculpture']::text[],'regional','Appalachian and Delta counties/parishes incl. Louisiana Delta parishes','emerging',0,true,DATE '2026-09-24','https://www.southarts.org/grants-opportunities/emerging-traditional-artists-program'),
('Louisiana Cultural Equity Arts & Creation Grant','New Orleans Jazz & Heritage Foundation','grant','Up to $7,500 for individuals who create, document or exhibit work that reflects or preserves Louisiana cultures.',0,7500,NULL,'https://www.jazzandheritage.org/community-partnership-grants/','Any Louisiana-based individual; priority for ALAANA and historically underrepresented artists. Work must take place in Louisiana. No fee. The 2026-27 deadline was July 8, 2026. The next cycle usually opens in late spring with an early-summer deadline.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'state','Louisiana','any',0,true,DATE '2026-09-24','https://www.jazzandheritage.org/community-partnership-grants/'),
('Joan Mitchell Center Artist-in-Residence','Joan Mitchell Foundation','residency','A 10-week (spring/fall) or 6-week (summer) residency at the Joan Mitchell Center in New Orleans with a private studio, weekday meals and a $150 weekly stipend.',900,1500,NULL,'https://www.joanmitchellfoundation.org/residencies','Visual artists 21+ who have lived in Orleans, Jefferson or Plaquemines Parish for 5+ years (or are natives), or past Joan Mitchell grantees. Not for students. No fee. The 2027 residency applications closed June 1, 2026. The window usually runs late March to early June.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'local','New Orleans (Orleans, Jefferson, Plaquemines)','any',0,true,DATE '2026-09-24','https://www.joanmitchellfoundation.org/residencies'),
('Louisiana Contemporary juried exhibition','Ogden Museum of Southern Art','open_call','Statewide juried exhibition at the Ogden Museum; Best in Show wins The Helis Foundation Art Prize ($5,000) and there are additional cash awards.',0,5000,NULL,'https://ogdenmuseum.org/','Louisiana residents 18+; work made in the last two years. 2026 fee was $40 for up to 3 entries. The 2026 call ran April 6 to May 22. The 2027 call isn''t posted yet but usually opens in early April.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'state','Louisiana','any',40,true,DATE '2026-09-24','https://ogdenmuseum.org/'),
('Platforms Fund','Antenna and Ashé Cultural Arts Center (Warhol Foundation Regional Regranting)','grant','$10,000 project grants for visual art or culture-bearer projects in public or non-traditional spaces, and $1,500 research and development grants.',1500,10000,NULL,'https://platformsfund.org/application/','Individual artists, collectives, curators and culture bearers who have lived in Greater New Orleans for 3+ years (Orleans, St. Bernard, Plaquemines, Jefferson, St. Tammany, or within 50 miles). Not for students. No fee. The application usually opens for the month of May.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'local','Greater New Orleans, LA','any',0,true,DATE '2026-09-24','https://platformsfund.org/application/'),
('Everett G. Powers Fund for Creativity','Arts Council of Greater Baton Rouge','award','One $5,000 award each year for a new creative project; it can cover fees, production costs, supplies and equipment rental.',5000,5000,'2026-10-29'::date,'https://www.artsbr.org/everett-g-powers','Individuals living in East Baton Rouge, West Baton Rouge, East Feliciana, West Feliciana, Iberville, Pointe Coupee, St. Helena, Ascension, Livingston or Tangipahoa Parish. All disciplines. Due 11:59pm Central; winner announced Nov 20, 2026. No fee is listed.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'local','Greater Baton Rouge, LA (10 parishes)','any',0,true,DATE '2026-09-24','https://www.artsbr.org/everett-g-powers'),
('Hambidge Creative Residency (Summer 2027)','The Hambidge Center','residency','A self-directed residency with a private studio in Rabun Gap, Georgia. Distinguished Fellowships waive fees for a 2-week stay and add a $700 stipend.',0,700,'2027-01-15'::date,'https://www.hambidge.org/guidelines-apply','Open nationally. $30 fee (waivers on request). Residents pay $300 per week (the actual cost is $2,250). Standing schedule: Summer applications Dec 1 to Jan 15; Fall March 1 to April 15; Spring Aug 1 to Sept 15.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'national','','any',30,true,DATE '2026-09-24','https://www.hambidge.org/guidelines-apply'),
('Penland Core Fellowship','Penland School of Craft','fellowship','A one-year fellowship in North Carolina with a $13,000 stipend, tuition for up to 7 workshops, housing and meals during sessions.',13000,13000,NULL,'https://penland.org/residencies/core-fellowship/','Early-career craft artists from anywhere. Confirm the SlideRoom fee before applying. The last deadline was June 15, 2026. Applications usually run April 15 to June 15.',ARRAY['ceramics','textile','printmaking','sculpture','photography','drawing','painting','mixed_media']::text[],'national','','emerging',0,true,DATE '2026-09-24','https://penland.org/residencies/core-fellowship/'),
('Atlantic Center for the Arts Mentoring Residency #199','Atlantic Center for the Arts','residency','A 3-week mentored residency (April 25 to May 15, 2027) in New Smyrna Beach, FL, working alongside painter Chase Hall or designer/artist Bob Faust.',0,0,'2027-02-25'::date,'https://atlanticcenterforthearts.org/residencies/mair-program/','Artists 21+ from anywhere. $25 fee. The residency costs $1,350 including room and board, and limited partial scholarships are available. Due 11:59pm EST.',ARRAY['painting','drawing','mixed_media','digital']::text[],'international','','any',25,true,DATE '2026-09-24','https://atlanticcenterforthearts.org/residencies/mair-program/'),
('Mississippi Artist Fellowship','Mississippi Arts Commission','fellowship','Up to $5,000 for Mississippi artists in visual arts, craft, design, public art and visual folk arts.',0,5000,NULL,'https://arts.ms.gov/grants/grants-for-individuals/artist-fellowships/','Permanent, full-time Mississippi residents. No fee. The deadline is usually around March 1; the FY2028 date isn''t posted yet.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'state','Mississippi','any',0,true,DATE '2026-09-24','https://arts.ms.gov/grants/grants-for-individuals/artist-fellowships/'),
('Tennessee Individual Artist Fellowship (FY2028)','Tennessee Arts Commission','fellowship','$5,000 fellowships for professional Tennessee artists. The FY2028 categories are 2D work, mural arts, craft and photography.',5000,5000,'2027-01-15'::date,'https://tnartscommission.org/grants/individual/','Professional artists 18+ who have lived in Tennessee for the past 3 years. Not for full-time students. Opens October 2026; due 11:59pm CST. No fee.',ARRAY['painting','drawing','printmaking','mixed_media','photography','ceramics','textile']::text[],'state','Tennessee','any',0,true,DATE '2026-09-24','https://tnartscommission.org/grants/individual/'),
('Alabama Individual Artist Fellowship','Alabama State Council on the Arts','fellowship','$7,500 fellowships in visual arts, craft, media arts and photography, and design.',7500,7500,NULL,'https://arts.alabama.gov/grants/howtoapply.aspx','Alabama residents for 2+ years. No fee. The window usually runs January 1 to early March; FY2028 dates aren''t posted yet.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'state','Alabama','any',0,true,DATE '2026-09-24','https://arts.alabama.gov/grants/howtoapply.aspx'),
('Alabama Quick Assist Grant for Individuals','Alabama State Council on the Arts','grant','$500 to $2,500 for special one-time needs.',500,2500,NULL,'https://arts.alabama.gov/grants/howtoapply.aspx','Rolling, year-round. Talk with Council staff before applying. For Alabama artists. No fee.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'state','Alabama','any',0,true,DATE '2026-09-24','https://arts.alabama.gov/grants/howtoapply.aspx'),
('South Carolina Individual Artist Fellowship (FY28)','South Carolina Arts Commission','fellowship','$10,000 fellowships. The FY28 disciplines include visual art, craft and interdisciplinary work.',10000,10000,NULL,'https://www.southcarolinaarts.com/grant/fel/','Artists 18+ who have lived in South Carolina for 2 years. Not for degree-seeking students. No fee. Applications open in fall 2026 but the deadline isn''t posted yet; the last cycle ran Jan 13 to Feb 26.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'state','South Carolina','any',0,true,DATE '2026-09-24','https://www.southcarolinaarts.com/grant/fel/'),
('Artadia Award, Atlanta','Artadia','award','Three unrestricted $15,000 awards for visual artists in metro Atlanta.',15000,15000,'2026-10-01'::date,'https://artadia.org/awards/','Visual artists who have lived and worked in eligible metro Atlanta counties for 2+ years. Not for art degree students. Free to apply.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'local','Metro Atlanta, GA','any',0,true,DATE '2026-09-24','https://artadia.org/awards/'),
('Southern Constellations Residency','Elsewhere','residency','A fully funded month-long residency in Greensboro, NC with room and board, travel support and a $1,000 honorarium.',1000,1000,NULL,'https://www.elsewheremuseum.org/southern-constellations','Artists based in or raised in the U.S. South (including LA, MS, AL, TX and GA). Mostly nominated, but self-nominations are welcome. Dates aren''t published; check the site.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'regional','U.S. South','any',0,true,DATE '2026-09-24','https://www.elsewheremuseum.org/southern-constellations'),
('1858 Prize for Contemporary Southern Art','Gibbes Museum of Art','award','An unrestricted $10,000 prize for one artist, with the work shown at the Gibbes in Charleston.',10000,10000,NULL,'https://www.gibbesmuseum.org/1858-prize/','Artists who live or work in, or are from, 14 Southern states including Louisiana. The fee was $35 in 2025. The 2026 deadline (Sept 14) has passed. It usually opens in summer with a late-summer or September deadline.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'regional','14 Southern states incl. Louisiana','any',35,true,DATE '2026-09-24','https://www.gibbesmuseum.org/1858-prize/'),
('NYSCA/NYFA Artist Fellowship','New York Foundation for the Arts','fellowship','An $8,000 unrestricted fellowship in rotating disciplines. The 2027 disciplines include painting and video/film.',8000,8000,NULL,'https://www.nyfa.org/awards-grants/nysca-nyfa-artist-fellowship/','New York State residents 25+ who have lived there 2+ years. Not for students. Free. The 2027 cycle opens this fall; the deadline is usually late January.',ARRAY['painting','digital','mixed_media']::text[],'state','New York State','any',0,true,DATE '2026-09-24','https://www.nyfa.org/awards-grants/nysca-nyfa-artist-fellowship/'),
('NYSCA State of the Arts Fellowship','New York State Council on the Arts','fellowship','$60,000 to place an artist inside a New York State agency for a socially engaged project, running February 2027 to spring 2028.',60000,60000,'2026-10-21'::date,'https://arts.ny.gov/SOAfellow','Solo artists 18+ living in New York State; experience with socially engaged practice. Apply to one host agency. Due 5pm. No fee.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'state','New York State','any',0,true,DATE '2026-09-24','https://arts.ny.gov/SOAfellow'),
('Pollock-Krasner Foundation Grant','The Pollock-Krasner Foundation','grant','Unrestricted grants of up to $50,000 (most are about $35,000) to support a year of work.',0,50000,NULL,'https://www.pkf.org/how-to-apply/','Rolling, accepted year-round (review takes 9 to 12 months). For painters, sculptors and artists working on paper, including printmakers. Requires about 10 exhibitions in the past 10 years. Not for students. No fee.',ARRAY['painting','sculpture','drawing','printmaking']::text[],'international','','established',0,true,DATE '2026-09-24','https://www.pkf.org/how-to-apply/'),
('Gottlieb Foundation Individual Support Grant','Adolph & Esther Gottlieb Foundation','grant','Unrestricted $25,000 grants for mature painters, sculptors and printmakers with financial need.',25000,25000,'2027-01-15'::date,'https://www.gottliebfoundation.org/individual-support-grant-1','Requires 20+ years in a mature phase of your work and current financial need (tax returns required). Opens Oct 15, 2026; due 11:59pm ET. No fee.',ARRAY['painting','sculpture','printmaking']::text[],'international','','established',0,true,DATE '2026-09-24','https://www.gottliebfoundation.org/individual-support-grant-1'),
('FCA Emergency Grants','Foundation for Contemporary Arts','grant','$500 to $3,000 for unexpected costs on experimental projects with confirmed public dates.',500,3000,NULL,'https://www.foundationforcontemporaryarts.org/grants/emergency-grants/','Rolling, year-round. Apply 8 to 10 weeks before the public date. For U.S.-based artists with a confirmed exhibition or performance. Not for students. No fee.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'national','','any',0,true,DATE '2026-09-24','https://www.foundationforcontemporaryarts.org/grants/emergency-grants/'),
('Creative Capital Award','Creative Capital','award','$15,000 to $50,000 unrestricted project grants plus professional development.',15000,50000,NULL,'https://creative-capital.org/creative-capital-award/','U.S. artists 25+, not students. Free. The open call usually runs early March to early April; the next dates aren''t posted yet.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'national','','any',0,true,DATE '2026-09-24','https://creative-capital.org/creative-capital-award/'),
('MacDowell Fellowship','MacDowell','residency','A residency of up to 8 weeks in Peterborough, NH with a studio, housing and meals. Need-based stipends of up to $1,500 and travel grants are available.',0,1500,'2027-02-10'::date,'https://www.macdowell.org/apply/apply-for-fellowship','Artists from all countries. $30 fee (hardship waiver available). The application opens Jan 15, 2027, for residencies Sept 2027 to Feb 2028.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'international','','any',30,true,DATE '2026-09-24','https://www.macdowell.org/apply/apply-for-fellowship'),
('Yaddo Residency','Yaddo','residency','A free residency with room, board and a studio in Saratoga Springs, NY.',0,0,'2026-12-20'::date,'https://yaddo.org/apply/','Visual artists and other disciplines. Not for degree students. $35 fee. The winter portal opens Nov 1 and closes Dec 20 at 11:59pm ET; confirm when it opens. Summer cycle: June 1 to July 1.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'national','','any',35,true,DATE '2026-09-24','https://yaddo.org/apply/'),
('Skowhegan Summer Residency 2027','Skowhegan School of Painting & Sculpture','residency','A 9-week summer residency in Maine (June 5 to Aug 7, 2027). Admission is need-blind, and most participants receive full scholarships.',0,0,'2026-10-16'::date,'https://skowheganart.org/school/','Artists 21+ from anywhere. $25 fee ($50 in the last two days). Due 11:59pm ET.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'international','','emerging',25,true,DATE '2026-09-24','https://skowheganart.org/school/'),
('Headlands Artist in Residence','Headlands Center for the Arts','residency','A fully sponsored 4 to 10 week residency near San Francisco with a studio, housing, meals, airfare and up to $1,000 a month.',0,2500,NULL,'https://www.headlands.org/program/air/','Artists at any stage, in any medium. Not for students. The fee was $35 to $45. Applications for 2028 residencies open in April 2027 (the last cycle ran April 1 to June 1).',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'international','','any',35,true,DATE '2026-09-24','https://www.headlands.org/program/air/'),
('Anderson Ranch Artists-in-Residence','Anderson Ranch Arts Center','residency','5- or 10-week residencies in Snowmass Village, CO; some are fully funded fellowships.',0,0,'2027-02-17'::date,'https://www.andersonranch.org/programs/artists-in-residence-program/','Artists 21+. $30 fee. Unless you receive a fellowship, residency fees are $750 to $1,500. The application goes live Dec 16, 2026.',ARRAY['painting','drawing','photography','digital','printmaking','sculpture','ceramics']::text[],'national','','any',30,true,DATE '2026-09-24','https://www.andersonranch.org/programs/artists-in-residence-program/'),
('Vermont Studio Center Residency & Fellowships','Vermont Studio Center','residency','2 to 4 week residencies in Johnson, VT. Everyone accepted gets at least a partial fellowship, and some get stipends of up to $1,000.',0,1000,'2026-09-30'::date,'https://vermontstudiocenter.org/apply','Artists from anywhere. $25 fee. Partial-fellowship residents pay $2,700 to $4,950. This call fills July to December 2027 residencies. The next call runs Feb 15 to Mar 31.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'international','','any',25,true,DATE '2026-09-24','https://vermontstudiocenter.org/apply'),
('Artadia Award, New York','Artadia','award','Three unrestricted $15,000 awards a year for NYC visual artists.',15000,15000,NULL,'https://artadia.org/awards/','Visual artists who have lived in the five boroughs for 2+ years. Not for art degree students. Free. The window is usually March 1 to April 1.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'local','New York City','any',0,true,DATE '2026-09-24','https://artadia.org/awards/'),
('Harpo Foundation Grants for Visual Artists','Harpo Foundation','grant','Up to $10,000 for under-recognized visual artists.',0,10000,NULL,'https://www.harpofoundation.org/grants/grants-for-visual-artists/','U.S. artists 21+, not in a fine arts degree program. $15 fee. Check back in February 2027; the deadline is usually late April.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'national','','any',15,true,DATE '2026-09-24','https://www.harpofoundation.org/grants/grants-for-visual-artists/'),
('Queer|Art|Mentorship','Queer|Art','fellowship','A 10-month mentorship for early-career LGBTQ+ artists with a $2,500 stipend and a retreat.',2500,2500,NULL,'https://www.queer-art.org/mentorship','U.S.-based LGBTQ+ early-career artists, not in school. Free. Part one is usually due mid-June.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'national','','emerging',0,true,DATE '2026-09-24','https://www.queer-art.org/mentorship'),
('Bronx Recognizes Its Own (BRIO)','Bronx Council on the Arts','award','$5,000 awards for Bronx artists, who complete a public service activity.',5000,5000,NULL,'https://www.bronxarts.org/grants/bronx-recognizes-its-own/','Bronx residents 18+, not full-time students. No fee. It usually opens in November with an early-January deadline.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'local','Bronx, NY','any',0,true,DATE '2026-09-24','https://www.bronxarts.org/grants/bronx-recognizes-its-own/'),
('Brooklyn Arts Fund','Brooklyn Arts Council','grant','$5,000 or $7,500 for public arts projects in Brooklyn during 2027.',5000,7500,'2026-10-11'::date,'https://www.brooklynartscouncil.org/what-we-do/grants/brooklyn-arts-fund','Brooklyn residents 18+, not full-time students. The project must be public and take place in Brooklyn in 2027. Due 11:59pm through Submittable. No fee.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'local','Brooklyn, NY','any',0,true,DATE '2026-09-24','https://www.brooklynartscouncil.org/what-we-do/grants/brooklyn-arts-fund'),
('Queens Arts Fund: New Work Grant','New York Foundation for the Arts','grant','$3,000 to $7,500 requests (at least 50% is funded) to create new work with a public component in Queens in 2027.',1500,7500,'2026-11-17'::date,'https://www.nyfa.org/awards-grants/queens-arts-fund-new-work-grant/','Queens residents, or artists with a full-time Queens studio, 18+. Not for students. Due 5pm ET. No fee.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'local','Queens, NY','any',0,true,DATE '2026-09-24','https://www.nyfa.org/awards-grants/queens-arts-fund-new-work-grant/'),
('Staten Island Arts Project Grants','Staten Island Arts','grant','$750 to $5,000 project grants for Staten Island artists; projects need a public component.',750,5000,NULL,'https://statenislandarts.org/grants/','Staten Island residents only. No fee. Opens Nov 16; the deadline is likely around Jan 31. Confirm when the portal opens.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'local','Staten Island, NY','any',0,true,DATE '2026-09-24','https://statenislandarts.org/grants/'),
('Smack Mellon Artist Studio Program','Smack Mellon','residency','An 11-month free private studio in DUMBO, Brooklyn for six early-career artists, plus a fellowship payment when funded.',0,0,NULL,'https://www.smackmellon.org/artist-studio/about/','NYC residents for 1+ year, 18+, not in a degree program. Free. The call usually opens in fall; last cycle''s deadline was Dec 1.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'local','New York City','emerging',0,true,DATE '2026-09-24','https://www.smackmellon.org/artist-studio/about/'),
('EFA Studio Program','Elizabeth Foundation for the Arts','residency','Subsidized, below-market private studios in Midtown Manhattan for up to 2 years.',0,0,NULL,'https://www.studios-efanyc.org/application-home','Visual artists who live within commuting distance of Manhattan. No fee to apply, but studios cost $634 to $2,022 a month plus dues. Applications open Oct 1, 2026; confirm the deadline (usually around Dec 1).',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'regional','New York City area','mid_career',0,true,DATE '2026-09-24','https://www.studios-efanyc.org/application-home'),
('LES Printshop Keyholder Residency','Lower East Side Printshop','residency','Nine months of free 24-hour printshop access in Manhattan, a $1,000 stipend and a show at the end.',1000,1000,'2027-05-31'::date,'https://www.printshop.org/keyholder-residency','Emerging artists in the NY metro area. Printmaking experience is helpful but not required. No fee. The Summer Keyholder residency ($500) is due Mar 1, 2027.',ARRAY['printmaking']::text[],'regional','New York metro','emerging',0,true,DATE '2026-09-24','https://www.printshop.org/keyholder-residency'),
('Artists Alliance LES Studio Program','Artists Alliance Inc.','residency','A free 3 or 6 month studio on the Lower East Side; New York State residents get a $500 monthly stipend.',1500,3000,NULL,'https://www.artistsallianceinc.org/programs/les-studio-program/','Emerging and mid-career artists, not students. No fee. Winter and summer calls are announced by newsletter; check the site.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'regional','Lower East Side, Manhattan','any',0,true,DATE '2026-09-24','https://www.artistsallianceinc.org/programs/les-studio-program/'),
('Jerome Hill Artist Fellowship','Jerome Foundation','fellowship','$60,000 over three years for early-career artists in Minnesota and NYC.',60000,60000,NULL,'https://www.jeromefdn.org/jerome-hill-artist-fellowship','Early-career artists living in Minnesota or the five boroughs. The next round opens in 2027; dates are TBA.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'regional','Minnesota and New York City','emerging',0,true,DATE '2026-09-24','https://www.jeromefdn.org/jerome-hill-artist-fellowship'),
('Wassaic Project Artist Residency','Wassaic Project','residency','Residencies in Dutchess County, NY on a sliding scale ($0 to $900 per session).',0,0,NULL,'https://www.wassaicproject.org/apply','Individuals, teams and families. $25 fee (waivable). The 2027 call has closed; the 2028 call isn''t announced yet.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'national','','any',25,true,DATE '2026-09-24','https://www.wassaicproject.org/apply'),
('Millay Arts Core Residency','Millay Arts','residency','A fully subsidized 2-week or 1-month residency in Austerlitz, NY; you pay only a $100 deposit.',0,0,'2026-10-01'::date,'https://www.millayarts.org/residencies/core-residency/','Multidisciplinary, blind jury. $45 fee (late deadline Oct 8, $65). For April to July 2027 sessions. The next deadline is March 1.',ARRAY['painting','photography','sculpture','mixed_media','digital','printmaking','ceramics','drawing','textile','installation']::text[],'national','','any',45,true,DATE '2026-09-24','https://www.millayarts.org/residencies/core-residency/')
) v(title, organization, opportunity_type, description, amount_min, amount_max, deadline, url, eligibility_notes, mediums, location_scope, location_detail, career_stage, application_fee, is_active, last_verified, source_url)
WHERE NOT EXISTS (SELECT 1 FROM public.opportunities o WHERE o.title = v.title AND o.organization = v.organization AND o.last_verified = DATE '2026-09-24');

SELECT count(*) FILTER (WHERE is_active) AS active,
       count(*) FILTER (WHERE is_active AND deadline >= current_date) AS dated,
       count(*) FILTER (WHERE is_active AND deadline IS NULL) AS rolling_or_tba
FROM public.opportunities;
